"""Generate Omnify logo size/format variations into assets/omnify-brand/."""
from __future__ import annotations

import shutil
import struct
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "omnify-brand"

SOURCE_CANDIDATES = [
    ROOT / "assets" / "omnify-icon-nested-source.png",
    Path(r"C:\Users\USER\.cursor\projects\d-jkglobal-01\assets\omnify-icon-nested.png"),
    ROOT / "assets" / "omnify-icon-300.png",
]

PNG_SIZES = [16, 32, 48, 64, 96, 128, 180, 192, 256, 300, 512, 1024]
WEBP_SIZES = [32, 64, 128, 192, 256, 512, 1024]
ICO_SIZES = [16, 32, 48]


def find_source() -> Path:
    for p in SOURCE_CANDIDATES:
        if p.is_file():
            return p
    raise FileNotFoundError("No Omnify logo source PNG found")


def load_master(source: Path) -> Image.Image:
    img = Image.open(source).convert("RGBA")
    if max(img.size) < 1024:
        img = img.resize((1024, 1024), Image.Resampling.LANCZOS)
    elif img.size != (1024, 1024):
        img = img.resize((1024, 1024), Image.Resampling.LANCZOS)
    return img


def save_png(img: Image.Image, path: Path, size: int) -> None:
    resized = img.resize((size, size), Image.Resampling.LANCZOS)
    resized.save(path, format="PNG", optimize=True)


def save_webp(img: Image.Image, path: Path, size: int) -> None:
    resized = img.resize((size, size), Image.Resampling.LANCZOS)
    resized.save(path, format="WEBP", quality=92, method=6)


def save_ico(sizes: dict[int, Image.Image], path: Path) -> None:
    images = [sizes[s] for s in ICO_SIZES]
    images[0].save(
        path,
        format="ICO",
        sizes=[(s, s) for s in ICO_SIZES],
        append_images=images[1:],
    )


def png_dimensions(path: Path) -> tuple[int, int]:
    with path.open("rb") as f:
        f.read(16)
        w, h = struct.unpack(">II", f.read(8))
    return w, h


def main() -> None:
    source = find_source()
    master = load_master(source)
    svg_src = ROOT / "assets" / "omnify-icon.svg"

    dirs = {
        "source": OUT / "source",
        "svg": OUT / "svg",
        "png": OUT / "png",
        "webp": OUT / "webp",
        "favicon": OUT / "favicon",
        "pwa": OUT / "pwa",
    }
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)

    master_path = dirs["source"] / "omnify-master-1024.png"
    master.save(master_path, format="PNG", optimize=True)

    if svg_src.is_file():
        shutil.copy2(svg_src, dirs["svg"] / "omnify-icon.svg")

    ico_images: dict[int, Image.Image] = {}
    manifest: list[str] = []

    for size in PNG_SIZES:
        out = dirs["png"] / f"omnify-{size}x{size}.png"
        save_png(master, out, size)
        manifest.append(f"png/omnify-{size}x{size}.png ({size}x{size})")
        if size in ICO_SIZES:
            ico_images[size] = Image.open(out).convert("RGBA")

    for size in WEBP_SIZES:
        out = dirs["webp"] / f"omnify-{size}x{size}.webp"
        save_webp(master, out, size)
        manifest.append(f"webp/omnify-{size}x{size}.webp ({size}x{size})")

    save_ico(ico_images, dirs["favicon"] / "favicon.ico")
    for size in ICO_SIZES:
        src = dirs["png"] / f"omnify-{size}x{size}.png"
        dst = dirs["favicon"] / f"favicon-{size}x{size}.png"
        shutil.copy2(src, dst)
    manifest.extend(["favicon/favicon.ico", "favicon/favicon-16x16.png", "favicon/favicon-32x32.png", "favicon/favicon-48x48.png"])

    pwa_map = {
        "apple-touch-icon-180x180.png": 180,
        "android-chrome-192x192.png": 192,
        "android-chrome-512x512.png": 512,
        "maskable-icon-512x512.png": 512,
    }
    for name, size in pwa_map.items():
        src = dirs["png"] / f"omnify-{size}x{size}.png"
        shutil.copy2(src, dirs["pwa"] / name)
        manifest.append(f"pwa/{name} ({size}x{size})")

    readme = f"""# Omnify Brand Assets

Omnify 로고 베리에이션 — 다양한 플랫폼·용도별 사용

## 폴더 구조

| 폴더 | 용도 |
|------|------|
| `source/` | 마스터 원본 (1024×1024 PNG) |
| `svg/` | 벡터 원본 (무한 확대) |
| `png/` | 표준 PNG (16~1024px) |
| `webp/` | WebP (32~1024px, 용량 최적화) |
| `favicon/` | favicon.ico + PNG 파비콘 |
| `pwa/` | Apple Touch · Android Chrome · PWA |

## 빠른 참조

| 용도 | 파일 |
|------|------|
| 웹 파비콘 | `favicon/favicon.ico` |
| iOS 홈 화면 | `pwa/apple-touch-icon-180x180.png` |
| Android / PWA | `pwa/android-chrome-192x192.png`, `pwa/android-chrome-512x512.png` |
| SNS 프로필 | `png/omnify-512x512.png` |
| 문서·제안서 | `png/omnify-300x300.png` |
| 앱스토어 | `png/omnify-1024x1024.png` |
| HTML `<link rel="icon">` | `png/omnify-32x32.png` 또는 `favicon/favicon-32x32.png` |

## 생성 정보

- Source: `{source.name}`
- Master: 1024×1024 PNG (LANCZOS 리사이즈)
- Generated by: `scripts/generate_omnify_brand_assets.py`

## 파일 목록

"""
    readme += "\n".join(f"- `{line}`" for line in manifest)

    (OUT / "README.md").write_text(readme, encoding="utf-8")

    legacy = ROOT / "assets" / "omnify-icon-300.png"
    shutil.copy2(dirs["png"] / "omnify-300x300.png", legacy)

    print(f"Done -> {OUT}")
    print(f"Master from: {source}")
    print(f"Legacy sync: {legacy}")
    print(f"Total files: {len(list(OUT.rglob('*'))) - len(list(OUT.rglob('*/')))}")


if __name__ == "__main__":
    main()
